name: Deploy Quartz Site
on:
  push:
    branches:
      - v4

permissions: 
  content: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Dependencies
        run: npm ci
    #Build your site
      - name: Build
        run: npx quartz build
        with:
          path: ./public

      # Create Credentials and get your site ID in the Worktree Cloud console,
      # then you're ready to deploy!
      - name: Deploy to Worktree Cloud Sites
        uses: worktree/deploy-site@v2
        with:
          source: ./public
          site_id: DdogiMYyHGcfgoUgZmkszU
          # Match names of secrets from step 5a
          public_key: ${{ secrets.WT_CLOUD_PUBLIC_KEY }}
          secret_key: ${{ secrets.WT_CLOUD_SECRET_KEY }}